<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace backend\controllers;
use Yii;
use common\models\Schoolcalendar;
use common\models\SchoolcalendarSearch;
use yii\web\Controller;
use yii\web\HttpException;
use yii\helpers\Url;
use yii\filters\AccessControl;
use dmstr\bootstrap\Tabs;

/**
* SchoolcalendarController implements the CRUD actions for Schoolcalendar model.
*/
class SchoolcalendarController extends Controller
{
public $layout="pmanager_layout";

/**
* @var boolean whether to enable CSRF validation for the actions in this controller.
* CSRF validation is enabled only when both this property and [[Request::enableCsrfValidation]] are true.
*/
public $enableCsrfValidation = false;


/**
* Lists all Schoolcalendar models.
* @return mixed
*/
public function actionIndex()
{
    $searchModel  = new SchoolcalendarSearch;
    $dataProvider = $searchModel->search($_GET);

Tabs::clearLocalStorage();

Url::remember();
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->render('index', [
'dataProvider' => $dataProvider,
    'searchModel' => $searchModel,
]);
}
public function actionEventad()
    {
	$evtid=$_GET["evtit"];
	$evsta=$_GET["evsta"];
	$evend=$_GET["evend"];
	$evmon=$_GET["evmon"];
	$evyer=$_GET["evyer"];
	$view=$_GET["view"];
	$calendarDataConfigID=$_GET["calendarDataConfigID"];
	$myid=Yii::$app->user->identity->id;
	
	return $this->renderPartial('adddataevent',['evtid'=>$evtid , 'evsta'=>$evsta, 'myid'=>$myid , 'evend'=>$evend , 'evmon'=>$evmon , 'evyer'=>$evyer , 'view'=>$view , 'sd'=>''  , 'calendarDataConfigID'=>$calendarDataConfigID]);
	}
	
	 public function actionActiondeletedata()
    {
   
        
        return $this->renderPartial('actiondeletedata');
    }  
	
/**
* Displays a single Schoolcalendar model.
* @param integer $id
*
* @return mixed
*/
public function actionView($id)
{
\Yii::$app->session['__crudReturnUrl'] = Url::previous();
Url::remember();
Tabs::rememberActiveState();

return $this->render('view', [
'model' => $this->findModel($id),
]);
}

/**
* Creates a new Schoolcalendar model.
* If creation is successful, the browser will be redirected to the 'view' page.
* @return mixed
*/
public function actionCreate()
{
$model = new Schoolcalendar;

try {
if ($model->load($_POST) && $model->save()) {
return $this->redirect(['view', 'id' => $model->id]);
} elseif (!\Yii::$app->request->isPost) {
$model->load($_GET);
}
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
$model->addError('_exception', $msg);
}
return $this->render('create', ['model' => $model]);
}

/**
* Updates an existing Schoolcalendar model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id
* @return mixed
*/
public function actionUpdate($id)
{
$model = $this->findModel($id);

if ($model->load($_POST) && $model->save()) {
return $this->redirect(Url::previous());
} else {
return $this->render('update', [
'model' => $model,
]);
}
}

/**
* Deletes an existing Schoolcalendar model.
* If deletion is successful, the browser will be redirected to the 'index' page.
* @param integer $id
* @return mixed
*/
public function actionDelete($id)
{
try {
$this->findModel($id)->delete();
} catch (\Exception $e) {
$msg = (isset($e->errorInfo[2]))?$e->errorInfo[2]:$e->getMessage();
\Yii::$app->getSession()->addFlash('error', $msg);
return $this->redirect(Url::previous());
}

// TODO: improve detection
$isPivot = strstr('$id',',');
if ($isPivot == true) {
return $this->redirect(Url::previous());
} elseif (isset(\Yii::$app->session['__crudReturnUrl']) && \Yii::$app->session['__crudReturnUrl'] != '/') {
Url::remember(null);
$url = \Yii::$app->session['__crudReturnUrl'];
\Yii::$app->session['__crudReturnUrl'] = null;

return $this->redirect($url);
} else {
return $this->redirect(['index']);
}
}

public function actionAdd()
{
	return $this->render('add',[
	'sd'=>0,
		'calendarDataConfigID'=>1,
	
	]);
}
public function actionEventdisp()
    {
	$evmon=$_GET["evmon"];
	$evyer=$_GET["evyer"];
	$view=$_GET["view"];
	$calendarDataConfigID=$_GET["calendarDataConfigID"];
	$myid=Yii::$app->user->identity->id;
	
	
	
	return $this->renderPartial('adddataevent',['evmon'=>$evmon , 'evyer'=>$evyer , 'myid'=>$myid, 'view'=>$view , 'sd'=>'' , 'calendarDataConfigID'=>$calendarDataConfigID ]);
	}
	
 public function actionCleardata()
    {
   
        
        return $this->renderPartial('cleardata');
    }  
	
	public function actionAddevent()
    {
	$das=$_GET["set"];
	
	return $this->renderPartial('/lunch/lunchsetup/addevent',['aderdate'=>$das]);
	}
/**
* Finds the Schoolcalendar model based on its primary key value.
* If the model is not found, a 404 HTTP exception will be thrown.
* @param integer $id
* @return Schoolcalendar the loaded model
* @throws HttpException if the model cannot be found
*/
protected function findModel($id)
{
if (($model = Schoolcalendar::findOne($id)) !== null) {
return $model;
} else {
throw new HttpException(404, 'The requested page does not exist.');
}
}
}
