<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\AddpropertyCSRhead */
?>
<div class="addproperty-csrhead-view">
 
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'user_id',
            'builder_id',
            'builder_total_area',
            'role_id',
            'project_name',
            'property_for',
            'project_type_id',
            'request_for',
            'featured_image:ntext',
            'featured_video:ntext',
            'city',
            'locality:ntext',
            'town_name',
            'sector_name',
            'address:ntext',
            'longitude',
            'latitude',
            'no_of_similiar_shops',
            'buildup_area',
            'build_unit',
            'expected_price',
            'asking_rental_price',
            'price_sq_ft',
            'price_acres',
            'price_negotiable',
            'revenue_lauout',
            'interior_details',
            'present_status',
            'jurisdiction_development',
            'shed_RCC',
            'maintenance_cost',
            'maintenance_cost_unit',
            'maintenance_by',
            'annual_dues_payable',
            'expected_rental',
            'membership_charge',
            'availability',
            'available_from',
            'available_date',
            'age_of_property',
            'possesion_by',
            'rental_type',
            'ownership',
            'ownership_status',
            'facing',
            'FAR_approval',
            'LOAN_taken',
            'min_super_area',
            'super_area',
            'super_unit',
            'carpet_area',
            'carpet_unit',
            'total_floors',
            'property_on_floor',
            'configuration',
            'floors_allowed_construction',
            'bedrooms',
            'bathrooms',
            'balconies',
            'pooja_room',
            'study_room',
            'servant_room',
            'other_room',
            'furnished_status',
            'parking',
            'is_active',
            'created_date',
            'status',
        ],
    ]) ?>

</div>
